name: Build Titanium with Paperclip and deploy as Action artifact

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Setup Gradle cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Git
        run: |
          git config --global user.email "titanium@titanvale.net"
          git config --global user.name "Titanium CI/CD"
          git config --global init.defaultBranch main
      - name: Grant execute permissions
        run: |
          chmod -R +x ./base/
          chmod -R +x ./scripts/
          chmod +x gradlew
          chmod +x titanium
      - name: Prepare Titanium upstream
        run: ./titanium upstream
      - name: Apply Titanium patches
        run: ./titanium apply
      - name: Build Titanium JAR
        run: ./gradlew build --no-daemon
      - name: Paperclip
        run: ./titanium paperclip
      - name: Copy Paperclip jar
        run: |
          cp -v "./Titanium-Server/build/libs/titanium.jar" "./titanium-$GITHUB_RUN_NUMBER.jar"
      - name: Upload Titanium artifact
        uses: actions/upload-artifact@v3
        with:
          name: Server JAR
          path: titanium-${{ github.run_number }}.jar
          if-no-files-found: error
