name: Release Build

on:
  push:
    branches: [ main ]
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Setup Gradle cache"
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - name: Setup Git
        run: |
          git config --global user.email "titanium@titanvale.net"
          git config --global user.name "Titanium CI/CD"
          git config --global init.defaultBranch main
      - name: Grant execute permissions
        run: |
          chmod -R +x ./base/
          chmod -R +x ./scripts/
          chmod +x gradlew
          chmod +x titanium
      - name: Prepare Titanium upstream
        run: ./titanium upstream
      - name: Apply Titanium patches
        run: ./titanium apply
      - name: Build Titanium JAR
        run: ./gradlew build --no-daemon
      - name: Paperclip
        run: ./titanium paperclip
      - name: Bump version and push tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.0.0
        with:
          configuration: "changelog_config.json"
          outputFile: ${{ github.workspace }}-CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          files: |
            Titanium-Server/build/libs/titanium.jar
        env:
          GITHUB_REPOSITORY: TitanVale/Titanium
